// Uygulama temaları için sabitler
export interface ThemeOption {
  id: string;
  name: string;
  colors: {
    // Genel tema renkleri
    primary: string;
    secondary: string;
    background: string;
    card: string;
    text: string;
    subText: string;
    border: string;
    // Bileşen özel renkleri
    cardBackground: string;
    cardBorder: string;
    headerBackground: string;
    buttonBackground: string;
    buttonText: string;
    // Durum renkleri
    success: string;
    warning: string;
    error: string;
    info: string;
  };
}

// Themes
export const THEMES: ThemeOption[] = [
  {
    id: 'default',
    name: 'Default',
    colors: {
      // Açık tema
      primary: '#6366F1',
      secondary: '#EC4899',
      background: '#FFFFFF',
      card: '#F5F5F7',
      text: '#000000',
      subText: '#00000080',
      border: '#E5E5E5',
      cardBackground: '#F5F5F7',
      cardBorder: '#E5E5E5',
      headerBackground: '#FFFFFF',
      buttonBackground: '#6366F1',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'enchantedDusk',
    name: 'Enchanted Dusk',
    colors: {
      primary: '#DA62C4',
      secondary: '#8B5CF6',
      background: '#FFFAFF',
      card: '#FFF0FB',
      text: '#4A2040',
      subText: '#7C4D6F',
      border: '#F8D7F5',
      cardBackground: '#FFF0FB',
      cardBorder: '#F8D7F5',
      headerBackground: '#FFFAFF',
      buttonBackground: '#DA62C4',
      buttonText: '#FFFFFF',
      success: '#34D399',
      warning: '#FBBF24',
      error: '#F87171',
      info: '#60A5FA',
    },
  },
  {
    id: 'nebulaNight',
    name: 'Nebula Night',
    colors: {
      primary: '#BD34FE',
      secondary: '#41C7FF',
      background: '#F8F7FF',
      card: '#F0ECFF',
      text: '#2D1B69',
      subText: '#4A3C7D',
      border: '#E1DAFF',
      cardBackground: '#F0ECFF',
      cardBorder: '#E1DAFF',
      headerBackground: '#F8F7FF',
      buttonBackground: '#BD34FE',
      buttonText: '#FFFFFF',
      success: '#0AD48B',
      warning: '#FFB443',
      error: '#FF5A5A',
      info: '#41C7FF',
    },
  },
  {
    id: 'auroraFlux',
    name: 'Aurora Flux',
    colors: {
      primary: '#7F5AF0',
      secondary: '#6EE7B7',
      background: '#F8FAFC',
      card: '#F1F5F9',
      text: '#0F172A',
      subText: '#334155',
      border: '#E2E8F0',
      cardBackground: '#F1F5F9',
      cardBorder: '#E2E8F0',
      headerBackground: '#F8FAFC',
      buttonBackground: '#7F5AF0',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'liquidGlass',
    name: 'Liquid Glass',
    colors: {
      primary: '#8ECDDD',
      secondary: '#22D3EE',
      background: '#F0FDFF',
      card: '#E0F7FA',
      text: '#164E63',
      subText: '#164E6380',
      border: '#BEE9F8',
      cardBackground: '#E0F7FA',
      cardBorder: '#BEE9F8',
      headerBackground: '#F0FDFF',
      buttonBackground: '#0EA5E9',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'royal',
    name: 'Royal Blue',
    colors: {
      primary: '#4338CA',
      secondary: '#3730A3',
      background: '#EEF2FF',
      card: '#E0E7FF',
      text: '#1E3A8A',
      subText: '#1E3A8A80',
      border: '#C7D2FE',
      cardBackground: '#E0E7FF',
      cardBorder: '#C7D2FE',
      headerBackground: '#EEF2FF',
      buttonBackground: '#4338CA',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    colors: {
      primary: '#0EA5E9',
      secondary: '#06B6D4',
      background: '#F0F9FF',
      card: '#E0F2FE',
      text: '#0C4A6E',
      subText: '#0C4A6E80',
      border: '#BAE6FD',
      cardBackground: '#E0F2FE',
      cardBorder: '#BAE6FD',
      headerBackground: '#F0F9FF',
      buttonBackground: '#0EA5E9',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    colors: {
      primary: '#16A34A',
      secondary: '#22C55E',
      background: '#F0FDF4',
      card: '#DCFCE7',
      text: '#14532D',
      subText: '#14532D80',
      border: '#BBF7D0',
      cardBackground: '#DCFCE7',
      cardBorder: '#BBF7D0',
      headerBackground: '#F0FDF4',
      buttonBackground: '#16A34A',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    colors: {
      primary: '#F97316',
      secondary: '#F43F5E',
      background: '#FFF7ED',
      card: '#FFEDD5',
      text: '#7C2D12',
      subText: '#7C2D1280',
      border: '#FED7AA',
      cardBackground: '#FFEDD5',
      cardBorder: '#FED7AA',
      headerBackground: '#FFF7ED',
      buttonBackground: '#F97316',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    colors: {
      primary: '#8B5CF6',
      secondary: '#A855F7',
      background: '#F5F3FF',
      card: '#EDE9FE',
      text: '#5B21B6',
      subText: '#5B21B680',
      border: '#DDD6FE',
      cardBackground: '#EDE9FE',
      cardBorder: '#DDD6FE',
      headerBackground: '#F5F3FF',
      buttonBackground: '#8B5CF6',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'cherry',
    name: 'Cherry Blossom',
    colors: {
      primary: '#FB7185',
      secondary: '#F472B6',
      background: '#FFF1F2',
      card: '#FFE4E6',
      text: '#881337',
      subText: '#9D174D80',
      border: '#FECDD3',
      cardBackground: '#FFE4E6',
      cardBorder: '#FECDD3',
      headerBackground: '#FFF1F2',
      buttonBackground: '#FB7185',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'mint',
    name: 'Mint',
    colors: {
      primary: '#14B8A6',
      secondary: '#2DD4BF',
      background: '#F0FDFA',
      card: '#CCFBF1',
      text: '#134E4A',
      subText: '#14532D80',
      border: '#99F6E4',
      cardBackground: '#CCFBF1',
      cardBorder: '#99F6E4',
      headerBackground: '#F0FDFA',
      buttonBackground: '#14B8A6',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'peach',
    name: 'Peach',
    colors: {
      primary: '#FB923C',
      secondary: '#FDBA74',
      background: '#FFF7ED',
      card: '#FFEDD5',
      text: '#7C2D12',
      subText: '#9A341280',
      border: '#FED7AA',
      cardBackground: '#FFEDD5',
      cardBorder: '#FED7AA',
      headerBackground: '#FFF7ED',
      buttonBackground: '#FB923C',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'sky',
    name: 'Sky',
    colors: {
      primary: '#0EA5E9',
      secondary: '#7DD3FC',
      background: '#F0F9FF',
      card: '#E0F2FE',
      text: '#0C4A6E',
      subText: '#07598580',
      border: '#BAE6FD',
      cardBackground: '#E0F2FE',
      cardBorder: '#BAE6FD',
      headerBackground: '#F0F9FF',
      buttonBackground: '#0EA5E9',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'grape',
    name: 'Grape',
    colors: {
      primary: '#A855F7',
      secondary: '#C084FC',
      background: '#FAF5FF',
      card: '#F3E8FF',
      text: '#581C87',
      subText: '#6B21A880',
      border: '#E9D5FF',
      cardBackground: '#F3E8FF',
      cardBorder: '#E9D5FF',
      headerBackground: '#FAF5FF',
      buttonBackground: '#A855F7',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'bloodMoon',
    name: 'Blood Moon',
    colors: {
      primary: '#DC2626',
      secondary: '#991B1B',
      background: '#FEF2F2',
      card: '#FEE2E2',
      text: '#450A0A',
      subText: '#991B1B',
      border: '#FECACA',
      cardBackground: '#FEE2E2',
      cardBorder: '#FECACA',
      headerBackground: '#FEF2F2',
      buttonBackground: '#DC2626',
      buttonText: '#FFFFFF',
      success: '#059669',
      warning: '#D97706',
      error: '#DC2626',
      info: '#2563EB',
    },
  },
  {
    id: 'goldenGod',
    name: 'Golden God',
    colors: {
      primary: '#FFD700',
      secondary: '#FFA500',
      background: '#FFFBEB',
      card: '#FEF3C7',
      text: '#451A03',
      subText: '#92400E',
      border: '#FDE68A',
      cardBackground: '#FEF3C7',
      cardBorder: '#FDE68A',
      headerBackground: '#FFFBEB',
      buttonBackground: '#FFD700',
      buttonText: '#000000',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
  {
    id: 'deepOcean',
    name: 'Deep Ocean',
    colors: {
      primary: '#0EA5E9',
      secondary: '#38BDF8',
      background: '#F0F9FF',
      card: '#E0F2FE',
      text: '#0C4A6E',
      subText: '#64748B',
      border: '#BAE6FD',
      cardBackground: '#E0F2FE',
      cardBorder: '#BAE6FD',
      headerBackground: '#F0F9FF',
      buttonBackground: '#0EA5E9',
      buttonText: '#FFFFFF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
  },
];

// Tema kimliğine göre tema seçme
export const getThemeById = (id: string): ThemeOption => {
  const theme = THEMES.find((theme) => theme.id === id);
  return theme || THEMES[0]; // Bulunamazsa varsayılan temayı döndür
};

// Koyu/açık tema modu ile tema kimliğine göre karma tema seçme
export const getThemeByIdAndMode = (id: string, isDark: boolean): ThemeOption => {
  // isDark true ise koyu renkli tema oluşturmak için ana temayı al
  if (!isDark) {
    return getThemeById(id); // Açık mod - direkt tema döndür
  }
  
  // Koyu mod için temanın koyu versiyonunu oluştur
  const lightTheme = getThemeById(id);
  
  // Her tema için özel koyu renkler
  const darkColors = {
    default: {
      background: '#121212',
      card: '#1F1F1F',
      headerBackground: '#121212',
      cardBackground: '#1F1F1F',
      cardBorder: '#2A2A2A',
      border: '#2A2A2A',
      text: '#FFFFFF',
      subText: '#FFFFFF80',
    },
    enchantedDusk: {
      background: '#2D0F2C',
      card: '#3D1E3C',
      headerBackground: '#2D0F2C',
      cardBackground: '#3D1E3C',
      cardBorder: '#4C2D4B',
      border: '#4C2D4B',
      text: '#FBE4F8',
      subText: '#E2B5DE',
    },
    nebulaNight: {
      background: '#0D0B21',
      card: '#191739',
      headerBackground: '#0D0B21',
      cardBackground: '#191739',
      cardBorder: '#2E2A5E',
      border: '#2E2A5E',
      text: '#F8F9FA',
      subText: '#CED4DA',
    },
    auroraFlux: {
      background: '#0F172A',
      card: '#1E293B',
      headerBackground: '#0F172A',
      cardBackground: '#1E293B',
      cardBorder: '#334155',
      border: '#334155',
      text: '#F8FAFC',
      subText: '#CBD5E1',
    },
    liquidGlass: {
      background: '#042F3B',
      card: '#0E4F65',
      headerBackground: '#042F3B',
      cardBackground: '#0E4F65',
      cardBorder: '#22D3EE',
      border: '#0E7490',
      text: '#E0F7FA',
      subText: '#E0F7FA80',
    },
    royal: {
      background: '#1E1B4B',
      card: '#2E2B6B',
      headerBackground: '#1E1B4B',
      cardBackground: '#2E2B6B',
      cardBorder: '#4338CA',
      border: '#3730A3',
      text: '#E0E7FF',
      subText: '#E0E7FF80',
    },
    ocean: {
      background: '#082F49',
      card: '#0C4A6E',
      headerBackground: '#082F49',
      cardBackground: '#0C4A6E',
      cardBorder: '#0EA5E9',
      border: '#0284C7',
      text: '#E0F2FE',
      subText: '#E0F2FE80',
    },
    forest: {
      background: '#052E16',
      card: '#14532D',
      headerBackground: '#052E16',
      cardBackground: '#14532D',
      cardBorder: '#16A34A',
      border: '#15803D',
      text: '#DCFCE7',
      subText: '#DCFCE780',
    },
    sunset: {
      background: '#431407',
      card: '#7C2D12',
      headerBackground: '#431407',
      cardBackground: '#7C2D12',
      cardBorder: '#F97316',
      border: '#EA580C',
      text: '#FFEDD5',
      subText: '#FFEDD580',
    },
    lavender: {
      background: '#2E1065',
      card: '#5B21B6',
      headerBackground: '#2E1065',
      cardBackground: '#5B21B6',
      cardBorder: '#8B5CF6',
      border: '#7C3AED',
      text: '#EDE9FE',
      subText: '#EDE9FE80',
    },
    cherry: {
      background: '#4C0519',
      card: '#881337',
      headerBackground: '#4C0519',
      cardBackground: '#881337',
      cardBorder: '#FB7185',
      border: '#E11D48',
      text: '#FFE4E6',
      subText: '#FFE4E680',
    },
    mint: {
      background: '#042F2E',
      card: '#134E4A',
      headerBackground: '#042F2E',
      cardBackground: '#134E4A',
      cardBorder: '#14B8A6',
      border: '#0D9488',
      text: '#CCFBF1',
      subText: '#CCFBF180',
    },
    peach: {
      background: '#431407',
      card: '#7C2D12',
      headerBackground: '#431407',
      cardBackground: '#7C2D12',
      cardBorder: '#FB923C',
      border: '#EA580C',
      text: '#FFEDD5',
      subText: '#FFEDD580',
    },
    sky: {
      background: '#082F49',
      card: '#0C4A6E',
      headerBackground: '#082F49',
      cardBackground: '#0C4A6E',
      cardBorder: '#0EA5E9',
      border: '#0284C7',
      text: '#E0F2FE',
      subText: '#E0F2FE80',
    },
    grape: {
      background: '#3B0764',
      card: '#581C87',
      headerBackground: '#3B0764',
      cardBackground: '#581C87',
      cardBorder: '#A855F7',
      border: '#9333EA',
      text: '#F3E8FF',
      subText: '#F3E8FF80',
    },
    bloodMoon: {
      background: '#0F0A0A',
      card: '#1C1212',
      headerBackground: '#0F0A0A',
      cardBackground: '#1C1212',
      cardBorder: '#DC2626',
      border: '#2A1A1A',
      text: '#FEF2F2',
      subText: '#7F7F7F',
    },
    goldenGod: {
      background: '#0C0A09',
      card: '#1C1917',
      headerBackground: '#0C0A09',
      cardBackground: '#1C1917',
      cardBorder: '#FFD700',
      border: '#292524',
      text: '#FEF3E2',
      subText: '#78716C',
    },
    deepOcean: {
      background: '#020617',
      card: '#0F172A',
      headerBackground: '#020617',
      cardBackground: '#0F172A',
      cardBorder: '#0EA5E9',
      border: '#1E293B',
      text: '#E0F2FE',
      subText: '#94A3B8',
    },
  };

  // Tema için özel koyu renkleri al
  const themeDarkColors = darkColors[id as keyof typeof darkColors] || darkColors.default;
  
  // Koyu tema versiyonu
  return {
    id: lightTheme.id,
    name: lightTheme.name,
    colors: {
      // Ana renkler korunur
      primary: lightTheme.colors.primary,
      secondary: lightTheme.colors.secondary,
      
      // Arka plan ve kart renkleri özel koyu renklere değiştirilir
      background: themeDarkColors.background,
      card: themeDarkColors.card,
      headerBackground: themeDarkColors.headerBackground,
      cardBackground: themeDarkColors.cardBackground,
      cardBorder: themeDarkColors.cardBorder,
      border: themeDarkColors.border,
      
      // Metin renkleri beyazlaştırılır
      text: themeDarkColors.text,
      subText: themeDarkColors.subText,
      buttonText: '#FFFFFF',
      
      // Buton renkleri korunur
      buttonBackground: lightTheme.colors.primary,
      
      // Durum renkleri korunur
      success: lightTheme.colors.success,
      warning: lightTheme.colors.warning,
      error: lightTheme.colors.error,
      info: lightTheme.colors.info,
    }
  };
}; 